# Generated by Django 5.0.3 on 2024-04-05 02:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='curso/')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido')], verbose_name='CPF')),
                ('date_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido')], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('date_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='treinamento.curso', verbose_name='Curso')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='treinamento.instrutor', verbose_name='Instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='QuantAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos_count', models.IntegerField()),
                ('cursos_count', models.IntegerField()),
                ('instrutores_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.curso')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.instrutor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
