# Generated by Django 5.0.3 on 2024-04-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantaluno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='quantaluno',
            name='instrutor',
        ),
        migrations.RemoveField(
            model_name='quantaluno',
            name='instrutores_count',
        ),
    ]
